version: '3.7'

services:

  mongo:
    image: mongo:3.6
    hostname: mongo
    command: mongod # just block access with firewall until i know what i'm doing here...
    volumes:
     - /docker/mongo/data:/data/db
     - /docker/mongo/config:/data/configdb
     - /docker/mongo/backup:/data/backup
    ports:
     - "27017:27017"

  unifi:
    image: jacobalberty/unifi:stable
    volumes:
      - /docker/unifi:/unifi
      - /docker/certs/etc/letsencrypt/archive/docker.mflit.com:/unifi/cert
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "10001:10001/udp"
    environment:
      BIND_PRIV: "false"
      RUNAS_UID0: "false"
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      # these vars are causing unifi to crash
      #CERTNAME: cert1.pem
      #CERT_PRIVATE_NAME: privkey1.pem
      #CERT_IS_CHAIN: 1
    depends_on:
      - mongo


  letsencrypt:
    image: linuxserver/letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - URL=docker.mflit.com
        # - SUBDOMAINS=unifi #,docker
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=unifi.mflit.com #optional
      - STAGING=false #optional
    volumes:
      - /docker/certs:/config
    ports:
      - 443:443
      - 80:80 #optional

